@dotnet_web_HostAddress = http://localhost:5227
@ContosoPizza_HostAddress = http://localhost:5227
GET {{dotnet_web_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

###
POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Paap's Pizza",
    "isGlutenFree": false
}

###
PUT {{ContosoPizza_HostAddress}}/pizza/4
Content-Type: application/json

{
    "id": 4,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###
DELETE {{ContosoPizza_HostAddress}}/pizza/4

###